# Generated by Django 5.2.5 on 2025-08-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_exerciseentry_0002_remove_trainer_role'),
        ('api', '0005_restore_trainer_role'),
    ]

    operations = [
    ]
