# Generated by Django 5.2.5 on 2025-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gymapprovalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='pending',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='gym',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='gym',
            name='is_approved',
        ),
    ]
